### ISSUE TITLE
Facilities Themes Pages

### ISSUE THREAD

**Issue by MarcoBarber** [gabzon/experiensa#15]
Elaborate a page template for each of the Facilities Themes with some text and a Picture

**Comment by gabzon** [comment]
@MarcoBarber Please send me the text and pictures

**Comment by MarcoBarber** [comment]
Please make a standard template with fake text and picture as done in other parts of the web as first step. In second step we place pictures from the catalog we received and capture missing ones together with text

**Comment by gabzon** [comment]
We've added the picture gallery in most of the facilities, i'll explain to you how to add the text, it is very easy
