### ISSUE TITLE
Testimonial section 2

### ISSUE THREAD

**Issue by MarcoBarber** [gabzon/experiensa#21]
Add a space for the user to write comments. They are to be validated by admin before publication. Can capture user picture from Facebook or Linkedin automatically.

**Comment by gabzon** [comment]
Users can comment their stayed on this website. http://bnb.experiensa.com/testimonials/
vb admin can validate comments in the backend of the website.
Capturing facebook and linkedin avatars automatically will be discussed in further releases.
