### ISSUE TITLE
VB Mobile Testimonials section, review sizing

### ISSUE THREAD

**Issue by gabzon** [gabzon/experiensa#41]

**Comment by valenciafg** [comment]
Fixed on SHA-2d2be90

**Comment by valenciafg** [comment]
Fixed by [https://github.com/gabzon/experiensa/commit/2d2be90ce0f2ae73a8d5bcbff1c07a69df533683](https://github.com/gabzon/experiensa/commit/2d2be90ce0f2ae73a8d5bcbff1c07a69df533683)
