### ISSUE TITLE
Indalo live composer foooter bug

### ISSUE THREAD

**Issue by gabzon** [gabzon/experiensa#57]
![screen shot 2017-02-18 at 19 16 22](https://cloud.githubusercontent.com/assets/142036/23095724/2b8cbf5e-f60f-11e6-8d2e-9085794dcb1c.jpg)

**Comment by valenciafg** [comment]
Fixed on https://github.com/gabzon/experiensa/commit/48f75c1e969d563fbeaaf1d1d3a17c8591c256be
